In [1]:
import pandas as pd

df = pd.read_parquet('../data/Processed Positions Data.parquet')
df = df.drop(columns=['gameId', 'gameDateTimeEst_player', 'coachId'])
df.head()

,firstName,lastName,personId,playerteamName,gameType_player,win_player,home_player,numMinutes_player,points_player,assists_player,...,turnoversPercent,fgRelativePercent,3pRelativePercent,ftRelativePercent,3PA_rate,trueShooting,eFG,FTA_rate,USG,Position
0,Rudy,Gobert,203497.0,Timberwolves,Playoffs,0.0,0.0,29.316668,3.0,2.0,...,0.0400,-0.006,-0.429,0.174,0.000000,0.614754,0.5,0.500000,4.850405,C
1,Mike,Conley,201144.0,Timberwolves,Playoffs,0.0,0.0,16.933332,4.0,4.0,...,0.0400,-0.006,-0.429,-0.826,0.000000,0.500000,0.5,0.000000,12.205674,PG
2,Spencer,Jones,1642461.0,Nuggets,Playoffs,1.0,1.0,36.933334,20.0,1.0,...,0.0625,0.212,0.421,0.200,0.555556,1.012146,1.0,0.222222,12.854611,SF
3,Christian,Braun,1631128.0,Nuggets,Playoffs,1.0,1.0,30.900000,9.0,3.0,...,0.0625,0.034,0.121,0.200,0.400000,0.765306,0.7,0.400000,9.715799,SG
4,Jaylen,Clark,1641740.0,Timberwolves,Playoffs,0.0,0.0,11.333333,0.0,1.0,...,0.0000,-0.506,-0.429,-0.826,0.000000,0.000000,0.0,0.000000,3.647343,SG

In [2]:
print(len(df))
df = df.reset_index(drop=True)
len(df.columns)

873494

97

In [3]:
# Drop all team statistics
df = df.drop(columns=[c for c in df.columns if '_team' in c])

In [4]:
team_stats = ['benchPoints', 'pointsFastBreak', 'pointsFromTurnovers',
              'pointsInThePaint', 'pointsSecondChance', 'reboundsTeam',
              'turnoversTeam', 'pointDifferential']
df = df.drop(columns=team_stats)

In [5]:
len(df.columns)

67

In [6]:
numeric_df = df.select_dtypes(include='number')
numeric_df = numeric_df.drop(columns=['personId'])
cols = list(numeric_df.columns) + ['gameType_player']
X = df[cols]
y = df['Position']

In [7]:
X = pd.get_dummies(X, columns=['gameType_player'])

In [8]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy="median")

X = pd.DataFrame(
    imputer.fit_transform(X),
    columns=X.columns,
    index = X.index
)

X = X.astype('float32')

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X = pd.DataFrame(scaler.fit_transform(X), columns=X.columns, index=X.index)

# Feature Reduction Aimed at Lowering Multicollinearity

In [ ]:
from utils import prune_redundant_features

kept_features, drop_cols = prune_redundant_features(X)

,Feature 1,Feature 2,Pearson Correlation,Abs Correlation
1258,playerteamId_player,gameType_player_All-Star Game,1.000000,1.000000
2210,gameType_player_Playoffs,gameType_player_Regular Season,-0.981975,0.981975
476,fieldGoalsAttempted_player,fieldGoalsAttemptedPercent,0.979899,0.979899
231,points_player,pointsPercent,0.972415,0.972415
923,freeThrowsPercentage_player,ftRelativePercent,0.971273,0.971273
535,fieldGoalsMade_player,fieldGoalsMadePercent,0.966293,0.966293
1065,reboundsTotal_player,reboundsTotalPercent,0.965540,0.965540
600,fieldGoalsPercentage_player,fgRelativePercent,0.960524,0.960524
605,fieldGoalsPercentage_player,eFG,0.960083,0.960083
1863,pointsPercent,fieldGoalsMadePercent,0.957867,0.957867
966,reboundsDefensive_player,reboundsDefensivePercent,0.956971,0.956971
199,points_player,fieldGoalsMade_player,0.951913,0.951913
2156,trueShooting,eFG,0.949423,0.949423
780,freeThrowsAttempted_player,freeThrowsMade_player,0.948533,0.948533
1980,freeThrowsAttemptedPercent,freeThrowsMadePercent,0.947536,0.947536
294,assists_player,assistsPercent,0.944757,0.944757
1192,plusMinusPoints_player,plusMinusPoints_per36,0.939566,0.939566
235,points_player,fieldGoalsMadePercent,0.930699,0.930699
1581,freeThrowsAttempted_per36,freeThrowsMade_per36,0.928206,0.928206
531,fieldGoalsMade_player,pointsPercent,0.927786,0.927786

In [ ]:
X = X.drop(columns=drop_cols)
print(len(X.columns))

30

In [13]:
X_sample = X.sample(n=100000, random_state=42)
y_sample = y.loc[X_sample.index]

In [15]:
%pip install boruta

Collecting boruta
  Using cached Boruta-0.4.3-py3-none-any.whl.metadata (8.8 kB)
Requirement already satisfied: numpy>=1.10.4 in c:\users\vtapi\anaconda3\lib\site-packages (from boruta) (2.3.5)
Requirement already satisfied: scikit-learn>=0.17.1 in c:\users\vtapi\anaconda3\lib\site-packages (from boruta) (1.7.2)
Requirement already satisfied: scipy>=0.17.0 in c:\users\vtapi\anaconda3\lib\site-packages (from boruta) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\vtapi\anaconda3\lib\site-packages (from scikit-learn>=0.17.1->boruta) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\vtapi\anaconda3\lib\site-packages (from scikit-learn>=0.17.1->boruta) (3.5.0)
Using cached Boruta-0.4.3-py3-none-any.whl (57 kB)
Installing collected packages: boruta
Successfully installed boruta-0.4.3
Note: you may need to restart the kernel to use updated packages.

# Boruta Selection

In [16]:
from sklearn.ensemble import RandomForestClassifier
from boruta import BorutaPy

rfc = RandomForestClassifier(n_estimators=200, n_jobs=-1, class_weight='balanced', random_state=42, max_depth=8)
boruta_selector = BorutaPy(rfc, n_estimators='auto', verbose=2, random_state=42, max_iter=100)
boruta_selector.fit(X_sample, y_sample)
important_features = X.columns[boruta_selector.support_]
weak_features = X.columns[boruta_selector.support_weak_]
print(important_features)
print(weak_features)

Iteration: 	1 / 100
Confirmed: 	0
Tentative: 	30
Rejected: 	0
Iteration: 	2 / 100
Confirmed: 	0
Tentative: 	30
Rejected: 	0
Iteration: 	3 / 100
Confirmed: 	0
Tentative: 	30
Rejected: 	0
Iteration: 	4 / 100
Confirmed: 	0
Tentative: 	30
Rejected: 	0
Iteration: 	5 / 100
Confirmed: 	0
Tentative: 	30
Rejected: 	0
Iteration: 	6 / 100
Confirmed: 	0
Tentative: 	30
Rejected: 	0
Iteration: 	7 / 100
Confirmed: 	0
Tentative: 	30
Rejected: 	0
Iteration: 	8 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	9 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	10 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	11 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	12 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	13 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	14 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	15 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	16 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	17 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	18 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	19 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	20 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	21 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	22 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	23 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	24 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	25 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	26 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	27 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	28 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	29 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	30 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	31 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	32 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	33 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	34 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	35 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	36 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	37 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	38 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	39 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	40 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	41 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	42 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	43 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	44 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	45 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	46 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	47 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	48 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	49 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	50 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	51 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	52 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	53 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	54 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	55 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	56 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	57 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	58 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	59 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	60 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	61 / 100
Confirmed: 	21
Tentative: 	1
Rejected: 	8
Iteration: 	62 / 100
Confirmed: 	21
Tentative: 	0
Rejected: 	9


BorutaPy finished running.

Iteration: 	63 / 100
Confirmed: 	21
Tentative: 	0
Rejected: 	9
Index(['numMinutes_player', 'steals_player', 'fieldGoalsMade_player',
       'threePointersAttempted_player', 'threePointersMade_player',
       'threePointersPercentage_player', 'freeThrowsPercentage_player',
       'reboundsDefensive_player', 'reboundsOffensive_player',
       'reboundsTotal_player', 'turnovers_player', 'plusMinusPoints_player',
       'assists_per36', 'blocks_per36', 'threePointersAttempted_per36',
       'foulsPersonal_per36', 'season', 'foulsPersonalPercent',
       'fgRelativePercent', 'FTA_rate', 'USG'],
      dtype='object')
Index([], dtype='object')